import sharp from "sharp";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { spawn } from "node:child_process";
import { fileURLToPath } from "node:url";

const W=1080,H=1920,FPS=30;
const outputDir=new URL("../output/reels/",import.meta.url), frameDir=new URL("../output/reel-frames/",import.meta.url);
const reels=JSON.parse(await readFile(new URL("../content/reels.json",import.meta.url),"utf8"));
const requested=process.argv[2], selected=requested?reels.filter(r=>r.slug===requested):reels;
if(!selected.length) throw new Error(`Unknown reel slug: ${requested}`);
const esc=v=>String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
function wrap(text,max=21){const lines=[];let line="";for(const word of text.split(/\s+/)){const next=line?`${line} ${word}`:word;if(next.length>max&&line){lines.push(line);line=word}else line=next}if(line)lines.push(line);return lines}
function promo(a,final=false){return final?`<rect x="74" y="1240" width="932" height="390" rx="44" fill="${a}"/><text x="540" y="1350" text-anchor="middle" fill="#07111f" font-size="48" font-weight="900">GET UP TO $250</text><text x="540" y="1425" text-anchor="middle" fill="#07111f" font-size="42" font-weight="900">IN BONUS BETS</text><text x="540" y="1530" text-anchor="middle" fill="#07111f" font-size="35" font-weight="900">USE CODE 4F273</text><text x="540" y="1590" text-anchor="middle" fill="#07111f" font-size="22" font-weight="800">FLIFF • 18+ • TERMS APPLY</text>`:`<rect x="620" y="1570" width="386" height="152" rx="26" fill="#0e1c2e" stroke="${a}" stroke-width="3"/><text x="650" y="1622" fill="#f7f9fc" font-size="24" font-weight="900">FLIFF</text><text x="976" y="1622" text-anchor="end" fill="${a}" font-size="24" font-weight="900">CODE 4F273</text><text x="650" y="1670" fill="#f7f9fc" font-size="19" font-weight="800">UP TO $250 BONUS BETS</text><text x="976" y="1705" text-anchor="end" fill="#8d9bb0" font-size="16" font-weight="800">18+ • TERMS APPLY</text>`}
function svg(r,i){const final=i===4,title=final?wrap("READY TO MAKE YOUR PICK?",18):i===0?wrap(r.hook):i===3?wrap(r.question):wrap(r.beats[i-1],24),label=final?"SPONSORED CTA":i===0?r.eyebrow:i===3?"YOUR TURN":`POINT 0${i}`,font=final?86:i===0?94:78,startY=final?470:i===0?520:650;return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}"><defs><radialGradient id="g" cx="80%" cy="10%"><stop offset="0" stop-color="${r.accent}" stop-opacity=".24"/><stop offset="1" stop-color="#07111f"/></radialGradient></defs><rect width="1080" height="1920" fill="url(#g)"/><circle cx="920" cy="380" r="310" fill="none" stroke="${r.accent}" stroke-width="4" opacity=".15"/><circle cx="920" cy="380" r="210" fill="none" stroke="${r.accent}" stroke-width="4" opacity=".1"/><path d="M-80 1230L1160 850" stroke="${r.accent}" stroke-width="120" opacity=".04"/><g font-family="Arial,Helvetica,sans-serif"><text x="74" y="112" fill="#f7f9fc" font-size="34" font-weight="900" letter-spacing="2">THE BALL DEPT.</text><text x="1006" y="112" text-anchor="end" fill="${r.accent}" font-size="23" font-weight="900">@THEBALLDEPT</text><rect x="74" y="230" width="${Math.min(760,92+label.length*20)}" height="64" rx="32" fill="${r.accent}"/><text x="104" y="272" fill="#07111f" font-size="24" font-weight="900">${esc(label)}</text>${title.map((line,n)=>`<text x="74" y="${startY+n*(font+24)}" fill="#f7f9fc" font-size="${font}" font-weight="900" letter-spacing="-3">${esc(line)}</text>`).join("")}${!final&&i>0&&i<4?`<text x="76" y="1040" fill="${r.accent}" font-size="170" font-weight="900">0${i}</text>`:""}${promo(r.accent,final)}<text x="74" y="1840" fill="#8190a5" font-size="17" font-weight="700">#AD • I MAY EARN REWARDS FROM QUALIFYING ACTIVITY</text></g></svg>`}
function ffmpeg(args){return new Promise((resolve,reject)=>{const child=spawn("ffmpeg",args,{stdio:["ignore","ignore","pipe"]});let error="";child.stderr.on("data",c=>error+=c);child.on("error",reject);child.on("close",code=>code===0?resolve():reject(new Error(error.slice(-4000))))})}
await mkdir(outputDir,{recursive:true});await mkdir(frameDir,{recursive:true});const manifest=[];
for(const reel of selected){const frames=[];for(let i=0;i<5;i++){const path=fileURLToPath(new URL(`${reel.slug}-${i}.png`,frameDir));await sharp(Buffer.from(svg(reel,i))).png().toFile(path);frames.push(path)}const output=fileURLToPath(new URL(`${reel.slug}.mp4`,outputDir));const inputs=frames.flatMap(path=>["-loop","1","-t","3","-i",path]);const filters=frames.map((_,i)=>`[${i}:v]scale=1120:1992,crop=1080:1920:x='20+10*sin(t*0.9+${i})':y='36+12*cos(t*0.7+${i})',fps=${FPS},format=yuv420p[v${i}]`).join(";")+";[v0][v1]xfade=transition=fade:duration=0.35:offset=2.65[x1];[x1][v2]xfade=transition=wipeleft:duration=0.35:offset=5.3[x2];[x2][v3]xfade=transition=fade:duration=0.35:offset=7.95[x3];[x3][v4]xfade=transition=slideup:duration=0.35:offset=10.6[out]";await ffmpeg(["-y",...inputs,"-filter_complex",filters,"-map","[out]","-t","13.6","-an","-c:v","libx264","-pix_fmt","yuv420p","-preset","medium","-crf","22","-movflags","+faststart",output]);const caption=`${reel.question}\n\nGet up to $250 in bonus bets on Fliff with code 4F273. 18+; terms apply. #ad I may earn rewards from qualifying activity.\n\n#sports #sportsdebate #theballdept #fliff`;manifest.push({...reel,video:`reels/${reel.slug}.mp4`,caption});console.log(`Generated ${reel.slug}.mp4`)}
await writeFile(new URL("../output/reels-manifest.json",import.meta.url),JSON.stringify(manifest,null,2));
